# Generated by Django 4.2.2 on 2023-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_country',
            field=models.CharField(choices=[('US', 'USA'), ('RU', 'Russia'), ('FR', 'France'), ('KR', 'South Korea'), ('DE', 'Germany')], default='US', max_length=2),
        ),
    ]
