# Generated by Django 4.2.2 on 2023-12-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Posts details', 'verbose_name_plural': 'Posts details'},
        ),
    ]
